#pragma once
#include <Arduino.h>

enum ScreenState : uint8_t {
  HOME,
  MAIN_MENU, ENV_MENU, VITALS_MENU, INVESTIGATE_MENU, SYSTEM_MENU, NAVIGATION_MENU,
  TEMP_SCREEN, HUMIDITY_SCREEN, LIGHT_SCREEN, SOUND_SCREEN, CONDITIONS_SCREEN,
  HEART_SCREEN, SIGNAL_SCREEN, MEASUREMENT_SCREEN,
  IR_REFLECTION_SCREEN, OBJECT_SCREEN, MAGNETIC_SCREEN, WATER_SCREEN, FLAME_SCREEN,
  POSITION_SCREEN, ALTITUDE_SCREEN, MOTION_SCREEN, NAV_STATUS_SCREEN,
  BATTERY_SCREEN, HARDWARE_SCREEN, SENSOR_STATUS_SCREEN, ABOUT_SCREEN, SETTINGS_SCREEN,
  SCREEN_COUNT
};

enum SystemStatus : uint8_t { STATUS_NORMAL, STATUS_WARNING, STATUS_CRITICAL };
inline const char* toString(SystemStatus s) {
  switch (s) {
    case STATUS_CRITICAL: return "CRITICAL";
    case STATUS_WARNING: return "WARNING";
    default: return "NORMAL";
  }
}
struct MenuItem { const char* label; ScreenState target; };
struct Menu { const char* title; const MenuItem* items; uint8_t count; };
